name: IndyCar secrets
run-name: IndyCar Driver App 🚀
on: [push]
env:
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
      
      - name: Create branch password
        uses: planetscale/create-branch-password-action@v1
        id: create_branch_password
        with:
          org_name: nathanjreese
          database_name: indycar
          branch_name: testnathah
          name: 'newpass2'
      - name: Get the credentials
        run: |
          echo "HOSTNAME: ${{ steps.create_branch_password.username }}"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
        env:
          VITE_DATABASE_URL: ${{ steps.create_branch_password.outputs.username }}
          VITE_DATABASE_USER: ${{ steps.create_branch_password.outputs.username }}
          VITE_DATABASE_PASSWORD: ${{ steps.create_branch_password.outputs.username }}
          