name: Create Branch
on: create
env:
  PLANET_SCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANET_SCALE_SERVICE_TOKEN_ID }}
  PLANET_SCALE_SERVICE_TOKEN: ${{ secrets.PLANET_SCALE_SERVICE_TOKEN }}
  
jobs:
  create_a_branch:
    runs_on: ubuntu-latest
    steps: 
      - name: Create Database Branch 
        uses: planetscale/create-branch-action@v4
        with:
          database_name: indycar
          branch_name: ps_action
          org_name: driverapp
  
