name: Create Branch
on: create
  
jobs:
  create_a_branch:
    runs-on: ubuntu-latest
    steps: 
      - name: Create Database Branch 
        uses: planetscale/create-branch-action@v4
        with:
          database_name: indycar
          branch_name: ps_action
          org_name: nathanjreese
          from: main
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
  
