name: Create Branch
on: create

env:
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
  
jobs:
  create_a_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Create Database Branch 
        uses: planetscale/create-branch-action@v4
        with:
          database_name: indycar
          branch_name: ${{ steps.extract_branch.outputs.branch }}
          org_name: nathanjreese
          from: main
      - name: Create branch password
        uses: planetscale/create-branch-password-action@v1
        id: create_branch_password
        with:
          org_name: nathanjreese
          database_name: indycar
          branch_name: ${{ steps.extract_branch.outputs.branch }}
          name: 'pass-${{ steps.extract_branch.outputs.branch }}'
      - name: Get the credentials
        run: |
          echo "VITE_DATABASE_URL: ${{ steps.create_branch_password.hostname }}"
          echo "VITE_DATABASE_USER: ${{ steps.create_branch_password.username }}"
          echo "VITE_DATABASE_PASSWORD: ${{ steps.create_branch_password.password }}"