name: Create Branch
on: create

env:
  PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
  PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
  
jobs:
  create_a_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Database Branch 
        uses: planetscale/create-branch-action@v4
        with:
          database_name: indycar
          branch_name: mynewbranch
          org_name: nathanjreese
          from: main
      - name: Create branch password
        uses: planetscale/create-branch-password-action@v1
        id: create_branch_password
        with:
          org_name: nathanjreese
          database_name: indycar
          branch_name: mynewbranch
          name: 'newpass'
      - name: Get the credentials
        run: |
          echo "Hostname: ${{ steps.create_branch_password.outputs.username }}"
        env:
          - VITE_DATABASE_URL: ${{ steps.create_branch_password.outputs.username }}
          - VITE_DATABASE_USER: "testtttt"
          - VITE_DATABASE_PASSWORD: ${{ steps.create_branch_password.outputs.password }}
  
